config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show]
  def index
    @flats = Flat.all
  end

  def show

  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>List of flats</h1>

<div class="container">
  <div class="row">
    <% @flats.each do |flat|%>
    <div class="col-xs-4">
      <div class="card-content">
        <div class="card-image" style="background-image: url('https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200')"></div>
        <div class="card-details">
          <h3><%= flat.name %></h3>
          <p><%= flat.address %></p>
          <div class="card-flex">
            <div><i class="fas fa-users"></i>    <%= flat.number_of_guests %></div>
            <div><i class="fas fa-pound-sign"></i>    <%= flat.price_per_night %></div>
          </div>
        </div>
        <div class="flat-options">
          <%= link_to "More details", flat_path(flat) %>
          <%= link_to "Edit", flats_path %>
          <%= link_to "Remove", flats_path %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200')">
</div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-xs-8">
      <div class="card-content show-card">
        <h2><%= @flat.name %></h2>
        <p><%= @flat.address %></p>
      </div>
      <div class="card-content show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="card-content show-card">
        <h3>Book this place!</h3>
      </div>
      <div class="card-content show-card">
        <h3>Details</h3>
        <div class="card-flex">
          <div><i class="fas fa-users"></i>    <%= @flat.number_of_guests %></div>
          <div><i class="fas fa-pound-sign"></i>    <%= @flat.price_per_night %></div>
        </div>
      </div>
      <div class="card-content show-card">
        <p>Share</p>  <i class="fab fa-facebook-square"></i>  <i class="fab fa-twitter-square"></i>  <i class="fab fa-pinterest-square"></i>  <i class="fas fa-envelope-square"></i>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <%= link_to "Home", flats_path, class: "home-button" %>
    </div>
    <%= yield %>
  </body>
</html>